# Generated by Django 5.1.5 on 2025-02-04 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_rename_fullname_user_user_name_team_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='is_active',
        ),
        migrations.AddField(
            model_name='team',
            name='user_email',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='team',
            name='user_type',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Proprietário', 'Proprietário'), ('Colaborador', 'Colaborador')], default='Colaborador', max_length=13),
        ),
        migrations.DeleteModel(
            name='Membership',
        ),
    ]
