# Generated by Django 5.1.5 on 2025-02-04 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_remove_user_user_name_team_slug_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='user_email',
        ),
        migrations.AddField(
            model_name='team',
            name='user_name',
            field=models.ForeignKey(default='USERNAME', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
