# Generated by Django 5.1.5 on 2025-02-05 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0007_remove_team_user_email_team_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='team',
            name='user_type',
        ),
        migrations.AddField(
            model_name='team',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('Administrador', 'Administrador'), ('Proprietário', 'Proprietário'), ('Colaborador', 'Colaborador')], default='Colaborador', max_length=13)),
                ('members', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team')),
            ],
        ),
    ]
