# Generated by Django 5.1.5 on 2025-02-05 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0008_remove_team_user_name_remove_team_user_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_name',
            field=models.CharField(blank=True, max_length=60, null=True, unique=True),
        ),
    ]
