# Generated by Django 5.1.5 on 2025-02-05 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0009_alter_team_team_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='owner',
        ),
        migrations.AlterField(
            model_name='membership',
            name='user_type',
            field=models.CharField(choices=[('Proprietário', 'Proprietário'), ('Administrador', 'Administrador'), ('Colaborador', 'Colaborador')], default='Colaborador', max_length=13),
        ),
    ]
