# Generated by Django 5.1.5 on 2025-02-07 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0011_alter_membership_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teams.team'),
        ),
    ]
