# Generated by Django 5.1.5 on 2025-02-10 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0012_user_current_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
