# Generated by Django 5.1.5 on 2025-02-11 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0014_user_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='full_name',
        ),
    ]
