# Generated by Django 5.1.5 on 2025-02-12 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0015_remove_user_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='members',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='membership', to=settings.AUTH_USER_MODEL),
        ),
    ]
