# Generated by Django 5.1.5 on 2025-02-11 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_membership_is_active_organization_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('master', 'Proprietário'), ('admin', 'Administrador'), ('member', 'Colaborador')], max_length=255),
        ),
    ]
