# Generated by Django 5.1.5 on 2025-02-04 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_funcao_options_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name_plural': 'User Profiles'},
        ),
        migrations.AlterUniqueTogether(
            name='userprofile',
            unique_together={('user', 'current_organization')},
        ),
    ]
