# Generated by Django 5.1.5 on 2025-02-05 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userprofile_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Funcao',
            new_name='Membership',
        ),
    ]
