# Generated by Django 5.1.5 on 2025-02-05 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_funcao_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.organization'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
