# Generated by Django 5.1.5 on 2025-02-03 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título da sua tarefa', max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('creation_at', models.DateTimeField()),
                ('finish_at', models.BooleanField(default=False)),
                ('category', models.CharField(max_length=20)),
            ],
        ),
    ]
