# Generated by Django 4.2.20 on 2025-03-20 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_remove_task_author_task_responsible'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('name', 'organization'), name='unique_category_per_org'),
        ),
    ]
