# Generated by Django 5.1.5 on 2025-02-12 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_category'),
        ('teams', '0015_remove_user_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='members',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='teams.membership'),
        ),
        migrations.AddField(
            model_name='task',
            name='team',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='teams.team'),
        ),
    ]
