# Generated by Django 5.1.5 on 2025-02-12 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_task_responsavel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('1', 'À fazer'), ('2', 'Fazendo'), ('3', 'Feito')], default='1', max_length=1),
        ),
    ]
