# Generated by Django 5.1.5 on 2025-02-13 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_remove_task_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='members',
            new_name='member',
        ),
        migrations.RemoveField(
            model_name='task',
            name='responsavel',
        ),
    ]
