# Generated by Django 5.1.5 on 2025-02-13 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_alter_task_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('À fazer', 'À fazer'), ('Fazendo', 'Fazendo'), ('Feito', 'Feito')], default='À fazer', max_length=7),
        ),
    ]
