# Generated by Django 5.1.5 on 2025-02-13 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_alter_task_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'À fazer'), ('doing', 'Fazendo'), ('done', 'Feito')], default='À fazer', max_length=7),
        ),
    ]
