# Generated by Django 5.1.5 on 2025-02-14 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'À fazer'), ('doing', 'Fazendo'), ('done', 'Feito')], default='todo', max_length=7),
        ),
    ]
