# Generated by Django 5.1.5 on 2025-03-10 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_organization_remove_customuser_name_team_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='username',
            new_name='name_user',
        ),
    ]
