# Generated by Django 5.1.5 on 2025-03-10 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_username_customuser_name_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='name_user',
            new_name='username',
        ),
    ]
