# Generated by Django 5.1.5 on 2025-03-10 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_rename_name_user_customuser_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='username',
            new_name='name_user',
        ),
    ]
