# Generated by Django 5.1.5 on 2025-03-10 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_rename_username_customuser_name_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MamberShip',
            new_name='Membership',
        ),
    ]
