# Generated by Django 4.2.20 on 2025-03-13 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_rename_mambership_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.AddField(
            model_name='organization',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('owner', 'dono'), ('admin', 'administrador'), ('member', 'membro')], default='member', max_length=20),
        ),
    ]
