# Generated by Django 4.2.20 on 2025-03-13 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_customuser_slug_alter_organization_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='slug',
        ),
    ]
