# Generated by Django 4.2.20 on 2025-03-13 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_remove_customuser_slug_remove_organization_slug'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
